version: '3.9'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - .:/app
    ports:
      - "3000:3000"
    environment:
     TZ: "${TZ:-America/Recife}"
     DB_HOST: postgres_blog
     DB_PORT: 5432
     DB_USERNAME: postgres
     DB_PWD: postgres
     DB_NAME: blog_db
    depends_on:
      - postgres_blog
    links:
      - postgres_blog
  postgres_blog:
    image: postgres:14
    restart: always
    ports:
      - 54322:5432
    environment:
      TZ: "${TZ:-America/Recife}"
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres      
    volumes:
    - ./tmp/postgres:/var/lib/postgresql/data